### ISSUE TITLE
Fails with JDK 11

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [jbossas/patch-gen#27]
executing the plugin with JDK 11 results in the following error. It works with JDK 8 though

```
java.io.IOException: org.jboss.modules.ModuleNotFoundException: java.se
	at org.jboss.as.patching.generator.DistributionProcessor.process(DistributionProcessor.java:106)
	at org.jboss.as.patching.generator.Distribution.create(Distribution.java:68)
	at org.jboss.as.patching.generator.PatchGenerator.process(PatchGenerator.java:129)
	at org.jboss.as.patching.generator.PatchGenerator.main(PatchGenerator.java:73)
Caused by: org.jboss.modules.ModuleNotFoundException: java.se
	at org.jboss.modules.Module.addPaths(Module.java:1266)
	at org.jboss.modules.Module.link(Module.java:1622)
	at org.jboss.modules.Module.relinkIfNecessary(Module.java:1650)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:296)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:280)
	at org.jboss.as.patching.generator.DistributionProcessor.process(DistributionProcessor.java:93)
	... 3 more
```

**Comment by htr3n** [comment]
You can temporarily add the configuration parameter `<argLine>` as following to give the plugin access to the `java.se` module.

```xml
<configuration>     
    <argLine>--add-modules=java.se</argLine>
</configuration>
```
