### ISSUE TITLE
Strange parsing error

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [jbossas/patch-gen#30]
The following file produces exception when plugin tries to parse it 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ JBoss, Home of Professional Open Source.
  ~ Copyright 2012, Red Hat, Inc., and individual contributors
  ~ as indicated by the @author tags. See the copyright.txt file in the
  ~ distribution for a full listing of individual contributors.
  ~
  ~ This is free software; you can redistribute it and/or modify it
  ~ under the terms of the GNU Lesser General Public License as
  ~ published by the Free Software Foundation; either version 2.1 of
  ~ the License, or (at your option) any later version.
  ~
  ~ This software is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  ~ Lesser General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Lesser General Public
  ~ License along with this software; if not, write to the Free
  ~ Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  ~ 02110-1301 USA, or see the FSF site: http://www.fsf.org.
  -->
<module name="org.jboss.as.version" xmlns="urn:jboss:module:1.9">
    <properties>
        <property name="jboss.api" value="private"/>
    </properties>

    <resources>
        <resource-root path="wildfly-version-15.0.1.Final.jar"/>
    </resources>

    <dependencies>
        <module name="org.jboss.modules"/>
    </dependencies>
</module>

```

The plugin tries to access "_modules\system\layers\base\org\jboss\as\version\main\module.xml_" and cannot parse it. But all my xml parsers are telling me this file is perfectly fine...

```
org.jboss.modules.xml.XmlPullParserException: Unexpected content of type 'element start' named 'module', text is: '<module name="org.jboss.as.version" xmlns="urn:jboss:module:1.9">' (position: START_TAG seen ...\n<module name="org.jboss.as.version" xmlns="urn:jboss:module:1.9">... @23:66) 
	at org.jboss.modules.xml.ModuleXmlParser.unexpectedContent(ModuleXmlParser.java:343)
	at org.jboss.modules.xml.ModuleXmlParser.validateNamespace(ModuleXmlParser.java:399)
	at org.jboss.modules.xml.ModuleXmlParser.parseDocument(ModuleXmlParser.java:437)
	at org.jboss.modules.xml.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:312)
	... 16 more
```

just for comparison. This one works:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ JBoss, Home of Professional Open Source.
  ~ Copyright 2012, Red Hat, Inc., and individual contributors
  ~ as indicated by the @author tags. See the copyright.txt file in the
  ~ distribution for a full listing of individual contributors.
  ~
  ~ This is free software; you can redistribute it and/or modify it
  ~ under the terms of the GNU Lesser General Public License as
  ~ published by the Free Software Foundation; either version 2.1 of
  ~ the License, or (at your option) any later version.
  ~
  ~ This software is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  ~ Lesser General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Lesser General Public
  ~ License along with this software; if not, write to the Free
  ~ Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  ~ 02110-1301 USA, or see the FSF site: http://www.fsf.org.
  -->
<module name="org.jboss.as.version" xmlns="urn:jboss:module:1.6">
    <properties>
        <property name="jboss.api" value="private"/>
    </properties>

    <resources>
        <resource-root path="wildfly-version-12.0.3.Final.jar"/>
    </resources>

    <dependencies>
        <module name="org.jboss.modules"/>
    </dependencies>
</module>

```

**Comment by Captain-P-Goldfish** [comment]
I checked a little bit and I have no idea why this should fail. But I tried the following and it would fix the problem:

```java
       try {
            PatchGenerator.main(args.toArray(new String[0]));
        }   catch (Exception ex) {
            getLog().error(ex);
            throw new MojoExecutionException( "Execution of PatchGenerator failed. See " + LOG_FILE + " for details." );
        }
```

is there a specific reason why you initiated an external jar instead of calling the sourcecode directly? Would you accept this (of course extended with the log-file output too) as pull-request?

**Comment by drichtarik** [comment]
I've also encountered this
